### Controller for publishing to the joint_states topic

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 125

### Gripper controller

gripper_controller:
  type: effort_controllers/GripperActionController
  joints:
    - $(arg side)_gripper_joint
  joint: $(arg side)_gripper_joint
  goal_tolerance: 0.05
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.2
  gains:
    $(arg side)_gripper_joint: {p: 5, i: 1, d: 1.5, i_clamp_min: -1, i_clamp_max: 1}

gripper_torque_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - $(arg side)_gripper_joint

### Joint controllers

joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  constraints:
    goal_time: 0.5
    $(arg side)_base_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_shoulder_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_shoulder_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_elbow_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_elbow_roll_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_wrist_lift_joint:
      trajectory: 0.5
      goal: 0.02
    $(arg side)_wrist_roll_joint:
      trajectory: 0.5
      goal: 0.02
  gains:
    $(arg side)_base_roll_joint: {p: 50, i: 8, d: 3.5, i_clamp_min: -150, i_clamp_max: 150}
    $(arg side)_shoulder_lift_joint: {p: 55, i: 12, d: 4, i_clamp_min: -80, i_clamp_max: 80}
    $(arg side)_shoulder_roll_joint: {p: 55, i: 20, d: 5, i_clamp_min: -80, i_clamp_max: 80}
    $(arg side)_elbow_lift_joint: {p: 40, i: 8, d: 4, i_clamp_min: -60, i_clamp_max: 60}
    $(arg side)_elbow_roll_joint: {p: 30, i: 20, d: 5, i_clamp_min: -80, i_clamp_max: 80}
    $(arg side)_wrist_lift_joint: {p: 45, i: 8, d: 2, i_clamp_min: -60, i_clamp_max: 60}
    $(arg side)_wrist_roll_joint: {p: 40, i: 10, d: 1, i_clamp_min: -80, i_clamp_max: 80}

joint_torque_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint

joint_position_controller:
  type: blue_controllers/BlueJointGroupPositionController
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  $(arg side)_base_roll_joint:
    pid: {p: 50, i: 5.0, d: 10, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_lift_joint:
    pid: {p: 40, i: 3, d: 10, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_roll_joint:
    pid: {p: 40, i: 3, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_lift_joint:
    pid: {p: 30, i: 2, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_roll_joint:
    pid: {p: 30, i: 2, d: 8, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_lift_joint:
    pid: {p: 20, i: 1, d: 5, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_roll_joint:
    pid: {p: 15, i: 1, d: 5, i_clamp_min: -1, i_clamp_max: 1}

joint_ctc:
  type: blue_controllers/BlueJointGroupCTC
  ctc_weight: 1.0
  joints:
    - $(arg side)_base_roll_joint
    - $(arg side)_shoulder_lift_joint
    - $(arg side)_shoulder_roll_joint
    - $(arg side)_elbow_lift_joint
    - $(arg side)_elbow_roll_joint
    - $(arg side)_wrist_lift_joint
    - $(arg side)_wrist_roll_joint
  $(arg side)_base_roll_joint:
    pid: {p: 200, i: 0.0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_lift_joint:
    pid: {p: 200, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_shoulder_roll_joint:
    pid: {p: 400, i: 0, d: 70, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_lift_joint:
    pid: {p: 100, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_elbow_roll_joint:
    pid: {p: 400, i: 0, d: 70, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_lift_joint:
    pid: {p: 100, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}
  $(arg side)_wrist_roll_joint:
    pid: {p: 400, i: 0, d: 50, i_clamp_min: -1, i_clamp_max: 1}

