koko_controllers:

  ### Controller for publishing to the joint_states topic

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  ### Gripper controller

  gripper_controller:
    type: effort_controllers/GripperActionController
    joint:  gripper_joint
    goal_tolerance: 0.01
    stalled_velocity_threshold: 0.01
    stall_timeout: 0.2
    gains:
      gripper_joint: {p: 10, i: 5, d: 1.5, i_clamp: 1}

  ### Joint controllers

  joint_torque_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - base_roll_joint
      - shoulder_lift_joint
      - shoulder_roll_joint
      - elbow_lift_joint
      - elbow_roll_joint
      - wrist_lift_joint
      - wrist_roll_joint

  joint_position_controller:
    type: koko_controllers/KokoJointGroupPositionController
    joints:
      - base_roll_joint
      - shoulder_lift_joint
      - shoulder_roll_joint
      - elbow_lift_joint
      - elbow_roll_joint
      - wrist_lift_joint
      - wrist_roll_joint
    base_roll_joint:
      pid: {p: 20, i: 0, d: 4, i_clamp: 0}
    shoulder_lift_joint:
      pid: {p: 20, i: 0, d: 3, i_clamp: 0}
    shoulder_roll_joint:
      pid: {p: 16, i: 0, d: 2.5, i_clamp: 0}
    elbow_lift_joint:
      pid: {p: 12, i: 0, d: 2.5, i_clamp: 0}
    elbow_roll_joint:
      pid: {p: 12, i: 0, d: 2.5, i_clamp: 0}
    wrist_lift_joint:
      pid: {p:  3, i: 0, d: 0.5, i_clamp: 0}
    wrist_roll_joint:
      pid: {p:  3, i: 0, d: 0.5, i_clamp: 0}

  cartesian_pose_controller:
    endlink: 'wrist_roll_link'
    paired_constraints: [1, 2, 3, 4, 5, 6]
    filter_length: 20
    type: koko_controllers/CartesianPoseController
    p_gains: [100, 100, 100, 4, 4, 4]
    d_gains: [0.1, 0.1, 0.1, 0.001, 0.001, 0.001]
    posture_control: true
    posture_gain: 18.0
    # posture_target: [0.0, 0.54, 1.19, -1.19, -1.33, 0.78, -2.29]
    posture_target: [0.0, -1.57, 0.0, -1.57, -1.57,-1.0, 0.0]
    z_offset_controller: 0.0
    root_name: koko
    base_roll_joint:
      id: 0.0
      d_gain: 3.0
      max_torque: 30
      min_torque: -30
      max_angle: 3.3
      min_angle: -2.2
    shoulder_lift_joint:
      id: 0.55
      d_gain: 3.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    shoulder_roll_joint:
      id: 0.5
      d_gain: 2.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    elbow_lift_joint:
      id: 0.7
      d_gain: 2.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    elbow_roll_joint:
      id: 0.0
      d_gain: 2.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    wrist_lift_joint:
      id: 0
      d_gain: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    wrist_roll_joint:
      id: 0.0
      d_gain: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
