DOF:
  joint_names: ['base_roll_joint', 'shoulder_lift_joint', 'shoulder_roll_joint', 'elbow_lift_joint', 'elbow_roll_joint']
  motor_names: ['base_roll_motor', 'right_motor1', 'left_motor1', 'right_motor2', 'left_motor2']
  gear_ratio: [7.1875, 7.1875, 7.1875, 7.1875, 7.1875]
  current_slope: [0.626, 0.626, 0.626, 0.626, 0.626]
  current_offset: [0.0, 0.0, 0.0, 0.0, 0.0]
  calibration_initial_angles: [-0.62, 0.99, 0.0, -0.83, 0.0]
  directions:        [1.0, -1.0, 1.0, -1.0, 1.0]
  torque_directions: [1.0, -1.0, 1.0, -1.0, 1.0]
  calibration_encoder: [4.4834423477927574, 4.4834423477927574, 3.5856800916826863, 4.4834423477927574, 3.5856800916826863] # deprecated
  calibration_joint_vive: [-0.2689415593931021, -0.2689415593931021, 0.085327798760949689, -0.2689415593931021, 0.085327798760949689] #deprecated
  #vive or rviz
  target_mode: "vive"
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  endlink_tracker: 'forearm_tracker_link'
  # Position Controllers ---------------------------------------
  simple_controller:
    endlink: 'forearm_link'
    paired_constraints: [1, 2, 3, 4]
    filter_length: 20
    type: my_controller/InverseDynamicsController
    root_name: DOF
    base_roll_joint:
      p: 200
      d: 0.0
      id: 1.5
      max_torque: 30
      min_torque: -30
      max_angle: 1.6
      min_angle: -1.4  
    shoulder_lift_joint:
      p: 400
      d: 0.0
      id: 10
      max_torque: 30
      min_torque: -30
      max_angle: 3.5
      min_angle: -1.4  
    shoulder_roll_joint:
      p: 200
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 1.5
      min_angle: -1.5  
    elbow_lift_joint:
      p: 300
      d: 0.02
      id: 5
      max_torque: 30
      min_torque: -30
      max_angle: 3.5
      min_angle: -1.4  
    elbow_roll_joint:
      p: 200
      d: 0.02
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 1.5
      min_angle: -1.5



