DOF:
  joint_names: ['base_roll_joint', 'shoulder_lift_joint', 'shoulder_roll_joint', 'elbow_lift_joint', 'elbow_roll_joint', 'wrist_lift_joint', 'wrist_roll_joint']
  motor_names: ['base_roll_motor', 'right_motor1', 'left_motor1', 'right_motor2', 'left_motor2', 'right_motor3', 'left_motor3']
  gear_ratio: [7.1875, 7.1875, 8.24448529412, 7.1875, 8.24448529412, 7.1875, 8.24448529412] # 8.24448529412 results from 7.1875 * (39 / 34) from the output gear
  current_slope: [0.626, 0.626, 0.626, 0.626, 0.626, 0.626, 0.626]
  current_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  calibration_initial_angles: [-0.0, 0.0, 0.0, -0.0, 0.0, 0.0, -3.0]
  hardstop_start_angles: [1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.1] # angles that you the robot is in for hardstop calibration
  directions:        [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0]
  torque_directions: [1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0]
  #directions:        [1.0, -1.0, 1.0, -0.0, 0.0, -0.0, 0.0]
  #torque_directions: [1.0, 1.0, -1.0, -0.0, 0.0, -0.0, 0.0]
  calibration_encoder: [4.4834423477927574, 4.4834423477927574, 3.5856800916826863, 4.4834423477927574, 3.5856800916826863, 4.4834423477927574, 3.5856800916826863] # deprecated
  calibration_joint_vive: [-0.2689415593931021, -0.2689415593931021, 0.085327798760949689, -0.2689415593931021, 0.085327798760949689, -0.2689415593931021, 0.085327798760949689] #deprecated
  #vive or rviz
  target_mode: "vive"
  # Publish all joint states -----------------------------------
  hardstop_torque_limit: 0.1
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  
  forearm_tracker: 'forearm_tracker_link'
  ee_tracker: 'ee_tracker_link'
  # Position Controllers ---------------------------------------
  simple_controller:
    endlink: 'wrist_roll_link'
    paired_constraints: [1, 2, 3, 4, 5, 6]
    filter_length: 20
    type: koko_controllers/CartesianPoseController
    p_gains: [400, 400, 400, 50, 50, 50]
    d_gains: [0, 0, 0, 0.0, 0.0, 0.0]
    posture_control: true
    posture_gain: 10.0
    #posture_target: [0.0, 0.54, 1.19, -1.19, -1.33, 0.78, -2.29] # for real control
    posture_target: [0.0, 0.62, 3.14, -0.67, 0.1, -0.67, 0.0] # for ball project
    z_offset_controller: 0.0
    root_name: DOF
    base_roll_joint:
      p: 40
      #d: 2.0
      d: 0.0
      id: 1.
      max_torque: 30
      min_torque: -30
      max_angle: 2.5
      min_angle: -2.5  
    shoulder_lift_joint:
      p: 40
      #d: 0.1
      d: 0.0
      id: 0.55
      max_torque: 30
      min_torque: -30
      max_angle: 2.2
      min_angle: -0.20  
    shoulder_roll_joint:
      p: 20
      #d: 0.1
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 3.75
      min_angle: -1.0 
    elbow_lift_joint:
      p: 25
      #d: 0.1
      d: 0.0
      id: 0.7
      max_torque: 30
      min_torque: -30
      max_angle: 0.4
      min_angle: -1.85
    elbow_roll_joint:
      p: 15
      #d: 0.1
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 1.2
      min_angle: -3.8
    wrist_lift_joint:
      p: 5
      #d: 0.1
      d: 0.0
      id: 1
      max_torque: 30
      min_torque: -30
      max_angle: 1.0
      min_angle: -1.5  
    wrist_roll_joint:
      p: 5
      #d: 0.1
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.7
      min_angle: -3.8



